# Generated by Django 4.2.1 on 2023-06-01 14:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import whoishere.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='to be auto populated', max_length=6, null=True, unique=True)),
                ('starts', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires', models.DateTimeField(blank=True, help_text='Leave blank to default to 30 minutes from now', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(default='W. Andrew Barr', max_length=100)),
                ('semester', models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall')], max_length=100)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2050)])),
                ('subject_code', models.CharField(choices=[('ANTH', 'ANTH'), ('HOMP', 'HOMP')], default='ANTH', max_length=4)),
                ('course_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1001), django.core.validators.MaxValueValidator(7000)])),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_first_name', models.CharField(max_length=100)),
                ('gw_email_handle', models.CharField(help_text='The part of your GW email address before @gwu.edu', max_length=100, validators=[
                    whoishere.models.email_handle_validator])),
                ('GWID', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^G[0-9]{8}$', 'Your GWID must be a capital G followed by 8 numbers')])),
                ('attendance_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whoishere.attendancepoll')),
            ],
        ),
        migrations.AddField(
            model_name='attendancepoll',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whoishere.course'),
        ),
    ]
